version: "3.3"
services:
  mongo-docker:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27018:27017
    container_name: mongo-docker
#    build:
#      context: ./docker/mongodb/
#      labels:
#        app: spring-security-rbac
#    ports:
#      - 27018:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: mongouser
#      MONGO_INITDB_ROOT_PASSWORD: password
#      MONGO_INITDB_DATABASE: admin
    volumes:
      - "spring-boot-mongodb_mongodata:/data/db"
    networks:
      - backend
  spring-security-rbac:
    container_name: spring-security-rbac-container
    build:
      context: .
      labels:
        app: spring-security-rbac
    ports:
      - "8080:8080"
    networks:
      - backend
    links:
      - mongo-docker
    depends_on:
      - mongo-docker
networks:
  backend:

volumes:
  spring-boot-mongodb_mongodata: